on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC16F877A
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC16F877A
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/3ac340158803f42119aa2dab9a96e817
          gist_title: Pr치ctica 19 - Bluetooth HM-10 PIC16F877A CCS.c
          gist_description: Pr치cticas PIC CCS
          github_file: Proyecto/PIC16F877A/Bluetooth HM-10.c
          file_encoding: WINDOWS-1252
    #PIC16F887
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC16F887
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/378b7e89500f079516c7e37b420ca8df
          gist_title: Pr치ctica 19 - Bluetooth HM-10 PIC16F887 CCS.c
          gist_description: Pr치cticas PIC CCS
          github_file: Proyecto/PIC16F887/Bluetooth HM-10.c
          file_encoding: WINDOWS-1252